name: ALZ-Bicep-2 Workflow

on:
  push:
    branches:
      - "main"
    paths:
      - "config/custom-parameters/roleAssignmentManagementGroup.servicePrincipal.parameters.all.json"
      - "config/custom-parameters/logging.parameters.all.json"
      - "config/custom-parameters/customPolicyDefinitions.parameters.all.json"
      - "config/custom-parameters/customRoleDefinitions.parameters.all.json"
      - "config/custom-parameters/managementGroups.parameters.all.json"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  LOCATION: "eastus2"
  UPSTREAM_RELEASE_VERSION: "v0.13.0"
  MANAGEMENT_SUBSCRIPTION_ID: "b6fb3c43-1fce-4636-a837-2ad04e1a5d5a"
  TOP_LEVEL_MG_PREFIX: "alz"

jobs:
  ALZ_Bicep_2_Workflow_Job:
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: OIDC Login to Tenant
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: "Role Assignments Deployment"
        uses: azure/powershell@v1
        with:
          inlineScript: |
            .\powershell-automation\pipeline-scripts\Deploy-RoleAssignments.ps1
          azPSVersion: "latest"

      - name: "Built-in and Custom Policy Assignments Deployment"
        uses: azure/powershell@v1
        with:
          inlineScript: |
            .\powershell-automation\pipeline-scripts\Deploy-PolicyAssignments.ps1
          azPSVersion: "latest"
