name: ALZ-Bicep-1 Workflow

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  LOCATION: "centralus"
  UPSTREAM_RELEASEVERSION: "v0.13.0"
  MANAGEMENT_SUBSCRIPTION_ID: "b6fb3c43-1fce-4636-a837-2ad04e1a5d5a"

jobs:
  bicep_tenant_deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: OIDC Login to Tenant
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: "Management Groups Deployment"
        uses: azure/powershell@v1
        with:
          inlineScript: |
            .\powershell-automation\pipeline-scripts\Deploy-ManagementGroups.ps1
          azPSVersion: "latest"

      - name: "Logging and Sentinel Deployment"
        uses: azure/powershell@v1
        with:
          inlineScript: |
            .\powershell-automation\pipeline-scripts\Deploy-LoggingAndSentinel.ps1
          azPSVersion: "latest"
